name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Checkout PR branch
      uses: actions/checkout@v3


    # go fmt only changes files.
    - name: Execute Go Fmt
      id: go-fmt
      run: |
        git fetch origin master
        files=$(git diff --name-status origin/master | grep ".go$" | awk '{print $2}')
        for x in $files
        do
            go fmt $x
        done
    - name: Commit and push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
        commit_user_name: 'tkpd-home-bot'
        commit_user_email: '111733097+tkpd-home-bot@users.noreply.github.com'
        commit_message: "[BOT] Autofix | Go Formatter"
