name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  golangci:
    name: lint
    runs-on: [runnerset=default-runners]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.14
      - uses: actions/checkout@v3
        with:
          # Default
          token: ${{ github.token }}
      - run: git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      - name: Get dependencies
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/golang/dep/cmd/dep
          dep ensure -v

      - name: Run unit-tests
        run: ./test.sh test.out 15
